"""empty message

Revision ID: 2d2028dbe770
Revises: a6deb5bf8eac
Create Date: 2020-05-16 15:26:59.223890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d2028dbe770'
down_revision = 'a6deb5bf8eac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('artist_id', sa.Integer(), nullable=False))
    op.drop_constraint('show_aritist_id_fkey', 'show', type_='foreignkey')
    op.create_foreign_key(None, 'show', 'artist', ['artist_id'], ['id'])
    op.drop_column('show', 'aritist_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('aritist_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'show', type_='foreignkey')
    op.create_foreign_key('show_aritist_id_fkey', 'show', 'artist', ['aritist_id'], ['id'])
    op.drop_column('show', 'artist_id')
    # ### end Alembic commands ###
